import React from 'react';

export default class SkilledIndependentVisas extends React.Component {
    render() {
        return (
            <div >
                <h4><strong>澳洲技术移民（EOI）</strong><strong>分数计算</strong></h4>
                <table border={1}>
                    <tbody>
                    <tr>
                        <td>
                            <p><strong><strong>澳洲技术移民打分（EOI)</strong></strong></p>
                        </td>
                        <td>
                            <p><strong><strong>澳大利亚技术移民打分详细说明</strong></strong></p>
                        </td>
                        <td>
                            <p><strong><strong>分数（EOI)</strong></strong></p>
                        </td>
                    </tr>
                    <tr>
                        <td rowSpan="5">
                            <p><strong><strong>年龄（Age）</strong></strong></p>
                        </td>
                        <td>
                            <p>18-24</p>
                        </td>
                        <td>
                            <p>25</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>25-32</p>
                        </td>
                        <td>
                            <p>30</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>33-39</p>
                        </td>
                        <td>
                            <p>25</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>40-44</p>
                        </td>
                        <td>
                            <p>15</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>45-49</p>
                        </td>
                        <td>
                            <p>0</p>
                        </td>
                    </tr>
                    <tr>
                        <td rowSpan="3">
                            <p><strong><strong>语言能力（English Language）</strong></strong></p>
                        </td>
                        <td>
                            <p>雅思单项4个6分（Competent English &ndash; IELTS)</p>
                        </td>
                        <td>
                            <p>0</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>雅思单项4个7分（proficient English &ndash; IELTS)</p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>雅思单项4个8分（superior English &ndash; IELTS8)</p>
                        </td>
                        <td>
                            <p>20</p>
                        </td>
                    </tr>
                    <tr>
                        <td rowSpan="4">
                            <p><strong><strong>与提名职业相关的澳洲工作经历</strong></strong></p>
                        </td>
                        <td>
                            <p>1-3年相关工作经历（过去10年）</p>
                        </td>
                        <td>
                            <p>5</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>3-5年年相关工作经验（过去10年）</p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>5-8年相关工作经验（过去10年）</p>
                        </td>
                        <td>
                            <p>15</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>8-10年相关工作经验（过去10年）</p>
                        </td>
                        <td>
                            <p>20</p>
                        </td>
                    </tr>
                    <tr>
                        <td rowSpan="3">
                            <p><strong><strong>与提名职业相关的海外工作经历</strong></strong></p>
                        </td>
                        <td>
                            <p>3-5年年相关工作经验（过去10年）</p>
                        </td>
                        <td>
                            <p>5</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>5-8年相关工作经验（过去10年）</p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>8-10年相关工作经验（过去10年）</p>
                        </td>
                        <td>
                            <p>15</p>
                        </td>
                    </tr>
                    <tr>
                        <td rowSpan="3">
                            <p><strong><strong>学历（包括海外学历和澳洲学历）</strong></strong></p>
                        </td>
                        <td width="361">
                            <p>认可海外学徒-Offshore recognised apprenticeship<br/>
                            澳洲三级证书-AQFⅢ/Ⅳ compeleted in Australia<br/>
                            澳洲文凭-Diploma completed inAustralia
                            </p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>学士（含荣誉学士和硕士）</p>
                        </td>
                        <td>
                            <p>15</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>博士-PHD</p>
                        </td>
                        <td>
                            <p>20</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>有STEM学历</strong></strong></p>
                        </td>
                        <td>
                            <p>完成至少2年的STEM相关专业的研究型硕士或博士课程</p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>澳洲学习</strong></strong></p>
                        </td>
                        <td>
                            <p>2年以上全日制学习</p>
                        </td>
                        <td>
                            <p>5</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>社区英语</strong></strong></p>
                        </td>
                        <td>
                            <p>NAATI认证（二级口译/三级笔译即可）</p>
                        </td>
                        <td>
                            <p>5</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>单身申请者</strong></strong></p>
                        </td>
                        <td>
                            <p>&nbsp;</p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td rowSpan="3">
                            <p><strong><strong>配偶</strong></strong></p>
                        </td>
                        <td>
                            <p>具备职业评估</p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>配偶如果是澳大利亚永居或公民</p>
                        </td>
                        <td>
                            <p>10</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>雅思4个6分（或等同于语言成绩）</p>
                        </td>
                        <td>
                            <p>5</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>职业年PY</strong></strong></p>
                        </td>
                        <td>
                            <p>提名职业相关专业（只有会计，工程，IT提供PY课程</p>
                        </td>
                        <td>
                            <p>5</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>州领地担保</strong></strong></p>
                        </td>
                        <td>
                            <p>适用于190州领担保</p>
                        </td>
                        <td>
                            <p>5</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>偏远地区担保</strong></strong></p>
                        </td>
                        <td>
                            <p>适用于州领地或者亲属担保的491偏远地区移民</p>
                        </td>
                        <td>
                            <p>15</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p><strong><strong>偏远地区学习</strong></strong></p>
                        </td>
                        <td>
                            <p>满足澳洲偏远地区2年学习的要求（高等教育）</p>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        )
    };
}

